language: r
sudo: false
cache: packages
warnings_are_errors: true

r:
  - oldrel
  - release
  - devel

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

script:
  - R CMD build .
  - R CMD check *tar.gz
